"""GENERATED BY scripts/scaffold.ts -- consolidated contract exports."""
from __future__ import annotations

from .transcription_short_clip_request import TranscriptionShortClipRequest
from .transcription_short_clip_response import TranscriptionShortClipResponse

__all__ = [
    "TranscriptionShortClipRequest",
    "TranscriptionShortClipResponse",
]
