"""GENERATED BY scripts/scaffold.ts -- TranscriptionShortClipRequest derived from schemas/transcription-short-clip-request.schema.json."""
from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class TranscriptionShortClipRequest(BaseModel):
    """Schema-aligned contract generated from docs/spec.md."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    clipId: str = Field(..., description="Identifier for the existing transcription job that produced an empty result.")
    sourcePath: str = Field(..., description="Absolute path to the normalized audio file replayed by the fallback pipeline.")
    forcedLanguage: Optional[str] = Field(
        None,
        description="Optional ISO language code to override detection; defaults to existing desktop flag.",
    )
    requestedBy: Optional[Literal["ui", "api", "automation"]] = Field(
        None,
        description="Actor initiating the fallback (ui|api|automation).",
    )
