export { default as Dashboard } from './Dashboard'
export { default as Upload } from './Upload'
export { default as Results } from './Results'
export { default as Analytics } from './Analytics'
export { default as Settings } from './Settings'
